// STORE RESET
export const RESET_REDUX_STORE = 'RESET_REDUX_STORE';

// AUTH x USER
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT = 'LOGOUT';
export const LOAD_PROFILE = 'LOAD_PROFILE';
export const LOGIN_REFRESH = 'LOGIN_REFRESH';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_PROFILE_PHOTO = 'UPDATE_PROFILE_PHOTO';
export const SET_USER_COORDS = 'SET_USER_COORDS';
export const UPDATE_MY_PROFILE = 'UPDATE_MY_PROFILE';
export const REMOVE_VIDEO_FROM_USER_VIDEO_LIST =
  'REMOVE_VIDEO_FROM_USER_VIDEO_LIST';
export const DO_PROFILE_UPDATE = 'DO_PROFILE_UPDATE';

// CALL
export const SETISVIDEOCALL = 'SETISVIDEOCALL';
export const END_VIDEO_CALL = 'END_VIDEO_CALL';
export const SET_CALLING_TO = 'SET_CALLING_TO';
export const REMOVE_CALLING_TO = 'REMOVE_CALLING_TO';
export const TOGGLE_IS_RECIVING = 'TOGGLE_IS_RECIVING';
export const SET_IS_ALREADY_IN_CALL = 'SET_IS_ALREADY_IN_CALL';
export const SET_CALL_ACTION = 'SET_CALL_ACTION';
export const SET_CALL_MODE = 'SET_CALL_MODE';
export const SET_CALLING_DATA = 'SET_CALLING_DATA';

// PROFILE
export const CURRENT_VIEW_PROFILE_REQUEST = 'CURRENT_VIEW_PROFILE_REQUEST';
export const CURRENT_VIEW_PROFILE_SUCCESS = 'CURRENT_VIEW_PROFILE_SUCCESS';
export const CURRENT_VIEW_PROFILE_FAIL = 'CURRENT_VIEW_PROFILE_FAIL';

export const PROFILE_LIST_MAIN_REQUEST = 'PROFILE_LIST_MAIN_REQUEST';
export const REMOVE_CURRENT_VIEW_PROFILE = 'REMOVE_CURRENT_VIEW_PROFILE';
export const PROFILE_LIST_MAIN_SUCCESS = 'PROFILE_LIST_MAIN_SUCCESS';
export const PROFILE_LIST_MAIN_FAIL = 'PROFILE_LIST_MAIN_FAIL';
export const PROFILE_LIST_REFRESH = 'PROFILE_LIST_REFRESH';

// FOLLOW
export const USER_FOLLOWERS_REQUEST = 'USER_FOLLOWERS_REQUEST';
export const USER_FOLLOWERS_SUCCESS = 'USER_FOLLOWERS_SUCCESS';
export const USER_FOLLOWERS_FAIL = 'USER_FOLLOWERS_FAIL';
export const REFRESH_FOLLOW_REDUCER = 'REFRESH_FOLLOW_REDUCER';
export const USER_FOLLOWING_REQUEST = 'USER_FOLLOWING_REQUEST';
export const USER_FOLLOWING_SUCCESS = 'USER_FOLLOWING_SUCCESS';
export const USER_FOLLOWING_FAIL = 'USER_FOLLOWING_FAIL';
export const SET_FOLLOWING_COUNT = 'SET_FOLLOWING_COUNT';
export const SET_FOLLOWER_COUNT = 'SET_FOLLOWER_COUNT';

// BLOCK
export const BLOCK_USER_REQUEST = 'BLOCK_USER_REQUEST';
export const BLOCK_USER_SUCCESS = 'BLOCK_USER_SUCCESS';
export const BLOCK_USER_FAIL = 'BLOCK_USER_FAIL';

export const UNBLOCK_USER_REQUEST = 'UNBLOCK_USER_REQUEST';
export const UNBLOCK_USER_SUCCESS = 'UNBLOCK_USER_SUCCESS';
export const UNBLOCK_USER_FAIL = 'UNBLOCK_USER_FAIL';

export const GET_BLOCKLIST_REQUEST = 'GET_BLOCKLIST_REQUEST';
export const GET_BLOCKLIST_SUCCESS = 'GET_BLOCKLIST_SUCCESS';
export const GET_BLOCKLIST_FAIL = 'GET_BLOCKLIST_FAIL';

export const BLOCK_REDUCER_REFRESH = 'BLOCK_REDUCER_REFRESH';

// CHAT
export const CHAT_REDUCER_REFRESH = 'CHAT_REDUCER_REFRESH';

export const CONVERSATION_LIST_REQUEST = 'CONVERSATION_LIST_REQUEST';
export const CONVERSATION_LIST_SUCCESS = 'CONVERSATION_LIST_SUCCESS';
export const CONVERSATION_LIST_FAIL = 'CONVERSATION_LIST_FAIL';

export const GET_OLD_CHAT_REQUEST = 'GET_OLD_CHAT_REQUEST';
export const GET_OLD_CHAT_SUCCESS = 'GET_OLD_CHAT_SUCCESS';
export const GET_OLD_CHAT_FAIL = 'GET_OLD_CHAT_FAIL';

export const DESTORY_CHAT_STORAGE = 'DESTORY_CHAT_STORAGE';
export const ADD_CHAT_STORAGE = 'ADD_CHAT_STORAGE';

// Notification
export const SET_LATEST_NOTIFICATION = 'SET_LATEST_NOTIFICATION';
export const ADD_TO_NOTIFICATION_STORAGE = 'ADD_TO_NOTIFICATION_STORAGE';
export const TEXT_MSG_RECIVED_NOTIFICATION = 'TEXT_MSG_RECIVED_NOTIFICATION';

//EXTRA
export const SET_CURRENT_ACTIVE_MAIN_TAB = 'SET_CURRENT_ACTIVE_MAIN_TAB';
export const SET_PREV_ACTIVE_MAIN_TAB = 'SET_PREV_ACTIVE_MAIN_TAB';

//POPUP
export const SET_POPUP_OVERLAY = 'SET_POPUP_OVERLAY';
export const REMOVE_POPUP_OVERLAY = 'REMOVE_POPUP_OVERLAY';
export const ADD_POPUP_OVERLAY = 'ADD_POPUP_OVERLAY';
export const REMOVE_OFFER_OVERLAY = 'REMOVE_OFFER_OVERLAY';
export const ADD_OFFER_OVERLAY = 'ADD_OFFER_OVERLAY';

//COIN
export const SET_SELECTED_COIN_FOR_PURCHASE = 'SET_SELECTED_COIN_FOR_PURCHASE';
export const REMOVE_SELECTED_COIN_FOR_PURCHASE =
  'REMOVE_SELECTED_COIN_FOR_PURCHASE';
export const GET_USER_COINS_COUNT_REQUEST = 'GET_USER_COINS_COUNT_REQUEST';
export const GET_USER_COINS_COUNT_FAIL = 'GET_USER_COINS_COUNT_FAIL';
export const GET_USER_COINS_COUNT_SUCCESS = 'GET_USER_COINS_COUNT_SUCCESS';
export const COIN_REDUCER_REFRESH = 'COIN_REDUCER_REFRESH';

//USER FILTER
export const GET_USERS_LIST_REQUEST = 'GET_USERS_LIST_REQUEST';
export const GET_USERS_LIST_FAIL = 'GET_USERS_LIST_FAIL';
export const GET_USERS_LIST_SUCCESS = 'GET_USERS_LIST_SUCCESS';
export const SET_USER_LIST_FILTER = 'SET_USER_LIST_FILTER';
export const USERS_REDUCER_REFRESH = 'USERS_REDUCER_REFRESH';
export const REMOVE_USERS_LIST = 'REMOVE_USERS_LIST';
export const REMOVE_USER_FROM_USERLIST = 'REMOVE_USER_FROM_USERLIST';
